config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    end

  resources :pins


    root 'home#index'

    get 'home/index'
    get 'mypins' => 'pins#mypins'
    get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinof"



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
  validates :photo, presence:true
  validates :description, presence:true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except:[ :index ]

  def pinsof
    @user_id = params[:user_id]
  end

  def mypins
    @pins = current_user.pins
  end

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        oktl_photo = Pin.last
        oktl_photo.update(user_id: current_user.id)
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :active, :user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/index.html.erb
<!--<meta charset="utf-8">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Orly - Bootstrap Bienvenido</title>
<link rel="stylesheet" href="bootstrap.min.css">
<link rel="stylesheet" href="main.css">
<link rel="stylesheet" href="responsive.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

<section class="banner" role="banner">
  <div class="banner-area">

    <div class="banner-area-gradient"></div>

    <div class="inner-bg">
      <div class="container">
        <div class="col-md-10 col-md-offset-1">
          <div class="banner-text text-center"> <a class="logo" href="#">Pinterest</a>
            <h1>Bienvenido CR</h1>

            <div id="countdown"></div>

            <a href="#subscribes" class="btn">Notify me</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="bootstrap.min.js"></script>
<script src="jquery.backstretch.min.js"></script>
<script src="jquery.countdown.js"></script>
<script type="text/javascript" src="jquery.subscribe.js"></script>
<script src="main.js"></script> -->


<div class="jumbotron">
  <div class="container">
    <h1  class="titulos">Pinterest</h1>
    <h2 class="titulos">Reconoces una gran idea en cuanto la ves.</h2>
    <p class="lead">
      <a class="btn btn-danger " href="https://www.pinterest.com.mx/login/"> Únete a Pinterest</a>

      <span class="oi" data-glyph="check"></span>
    </p>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-4">

      <div class="page-header"><h1>CONOCE</h1></div>
      <p>“Pinterest es el motor de descubrimiento visual. Nuestra misión consiste en ayudar a las personas a descubrir y hacer lo que les gusta.”</p>
      <img  src="https://3.bp.blogspot.com/--JTBSOWHjcA/VpW8siKcRlI/AAAAAAAAI88/R4BYwtI44vU/s1600/pinterest-social-media-icon.png" class="img-responsive">


    </div>

    <div class="col-md-4">
      <a style="display:inline"  href="https://newsroom.pinterest.com/es/post/las-100-ideas-pinterest-para-probar-en-el-2018" target="_blank">Las 100 ideas Pinterest para probar en el 2018</a>
      <span class="badge badge-secondary">New</span></h6>
      <p class="titulos">¡Los resultados están listos y tenemos mucho para esperar del 2018! Ruedas para yoga, cruceros fluviales y los “derma rollers” son solo algunas de las tendencias emergentes que entusiasman a los usuarios de Pinterest. Nuestro reporte sobre 100 ideas Pinterest lo tiene todo. Se trata de 100 predicciones de tendencias dentro de nuestras principales categorías respaldadas por datos globales. Cada categoría está llena de sorpresas que no te puedes perder, así que prepárate para hacer un lugar en tu corazón a tus próximos Pines favoritos.</p>
    </div>

    <div class="col-md-4">
      <h3>Blog.pinterest.com</h3>
      <p>San Francisco, California / Pinterest is full of possibilities to design your life. Discover recipes, style inspiration, projects for your home and other ideas to try.</p>


      <hr>

      <ul>
        <li>°Emprende en el mundo digital</li>
        <li>°Empieza desde cero</li>
        <li>°Ve la matrix</li>
      </ul>



    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterest</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>


   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script type="text/javascript" scr="//cdnjs.cloudflare.com/ajax/libs/masonry/4.2.1/masonry.pkgd.min.js">

    </script>

  </head>



  <body>

<%= render 'shared/navbar'%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


  <%= yield%>



  </body>


</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin, local: true) do |form| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Foto" %>
    <%= form.text_field :photo, id: :pin_photo, :class=>'form-control', :placeholder=> "URL de la foto" %>
  </div>

    <div class="form-group">
  <div class="field">
    <%= form.label :name, "Descripcion" %>
    <%= form.text_area :description, id: :pin_description,:class=>'form-control',  :placeholder=> "Descripción", :rows=>"3", :cols=> "10" %>
      </div>
    </div>

    <div class="form-group">
  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :pin_active %>
  </div>
    </div>

    <div class="form-group" >
      <div class="field">
        <%= form.label 'create', hidden:true  %>
        <%= form.text_field :user_id,:value => current_user.id, hidden:true%>
      </div>
    </div>

    <div class="actions">
    <%= form.submit "Crear", :class =>"btn btn-primary"%>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">
<h1>Editar Pin</h1>

  <div class="row">
    <div class="col-md-6 ">
<%= render 'form', pin: @pin %>
    </div>
  </div>
<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<h1>Tu eres la vista de Pins</h1>

<div id="container">


    <% @pins.each do |pin| %>
        <div class="item" style="width:25%">
          <div class="thumbnail">


        <%= image_tag(pin.photo, style:'width:100px') %>
       <%= pin.description %>
        <%= pin.active %>
            <div class="buttons" style="margin-top:10px; margin-bottom:10px">
        <%= link_to 'Show', pin, :class=> 'btn' %>
        <%= link_to 'Edit', edit_pin_path(pin),:class=> 'btn' %>
              <% if user_signed_in? %>
              <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' },:class=> 'btn' %>
              <% end %>
            </div>
  </div>
  </div>
  <% end %>

  <br>
  <% if user_signed_in? %>
  <%= link_to 'New Pin', new_pin_path %>
      <% end %>
</div>

<script type="text/javascript">
    var $container = $ ('#container');
    //initialize
    $container.masonry({
        columnWidth:200,
        itemSelector: '.item'
    });
  $(window).load(function(){
var $container = $ ('#container');
//initialize
    $container.masonry({
        columnWidth:200,
        itemSelector: '.item'
    });
  })
</script>

app/views/pins/mypins.html.erb

<div class="container">
  <h1>Mis Pins</h1>

  <% @pins.each do |pin| %>
      <div class="col-md-5">
        <div class="thumbnail">


          <%= image_tag(pin.photo, style:'width:100px') %>
          <%= pin.description %>
          <%= pin.active %>
          <div class="buttons" style="margin-top:10px; margin-bottom:10px">
            <%= link_to 'Show', pin, :class=> 'btn' %>
            <%= link_to 'Edit', edit_pin_path(pin),:class=> 'btn' %>
            <% if user_signed_in? %>
                <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' },:class=> 'btn' %>
            <% end %>
          </div>
        </div>
      </div>
  <% end %>

  <br>
  <% if user_signed_in? %>
      <%= link_to 'New Pin', new_pin_path %>
  <% end %>
</div>

app/views/pins/new.html.erb
<div class="container">
<h1>Agregar Nuevo Pin</h1>
<div class="row">
<div class="col-md-6 ">
<%= render 'form', pin: @pin %>
</div>
</div>
<%= link_to 'Back', pins_path %>
</div>

app/views/pins/pinsof.html.erb
Nueva
<%= @user_id%>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
  <%=image_tag(@pin.photo, style: 'width:250px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @pin.active %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>
<%= link_to "Mas pins del mismo usuario", pinof_path(@pin.user.id)%>

app/views/shared/_navbar.html.erb


<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom:0px;">
  <a class="navbar-brand" href="<%=home_index_path%>">Mi Pinterest</a>
 <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>-->
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li><a class="nav-link" href="<%=pins_path%>">Pin <span class="sr-only">(current)</span></a></li>
      <li><a class="nav-link" href="<%=mypins_path%>">Mis Pins <span class="sr-only">(current)</span></a></li>
      <% if current_user.nil? %>
      <li class="nav-item"><a class="nav-link" href="<%=new_user_session_path%>">Ingreso</a></li>
      <li class="nav-item"><a class="nav-link" href="<%=new_user_registration_path%>">Registro</a></li>
        <% else %>
      <li class="nav-item">
        <a class="nav-link" <%= link_to "Salir", destroy_user_session_path, method: :delete%> </li>
      </li>
         <% end %>
    </ul>

  </div>
</nav>